In [37]:
import pandas as pd
import requests

# Fetch the data.
df = pd.read_csv("https://ourworldindata.org/grapher/life-expectancy.csv?v=1&csvType=full&useColumnShortNames=true", storage_options = {'User-Agent': 'Our World In Data data fetch/1.0'})

# Fetch the metadata
metadata = requests.get("https://ourworldindata.org/grapher/life-expectancy.metadata.json?v=1&csvType=full&useColumnShortNames=true").json()

In [26]:
df.head(3)

        entity code  year  life_expectancy_0
0  Afghanistan  AFG  1950            28.1563
1  Afghanistan  AFG  1951            28.5836
2  Afghanistan  AFG  1952            29.0138

In [27]:
df.shape

(21565, 4)

In [6]:
df.dtypes

entity                   str
code                     str
year                   int64
life_expectancy_0    float64
dtype: object

In [28]:
df.columns.tolist()

['entity', 'code', 'year', 'life_expectancy_0']

In [29]:
df.rename(columns={"entity": "Pais"}, inplace=True) #modificar/cambiar el nombre de los indices

In [14]:
df[df["Pais"].str.contains("k", regex=True)] #extraer cadenas de texto que contengan la letra k

               Pais code  year  life_expectancy_0
2795   Burkina Faso  BFA  1950            33.0262
2796   Burkina Faso  BFA  1951            33.3732
2797   Burkina Faso  BFA  1952            33.6027
2798   Burkina Faso  BFA  1953            33.8987
2799   Burkina Faso  BFA  1954            34.1847
...             ...  ...   ...                ...
20808    Uzbekistan  UZB  2019            72.0934
20809    Uzbekistan  UZB  2020            71.4613
20810    Uzbekistan  UZB  2021            71.6808
20811    Uzbekistan  UZB  2022            72.1465
20812    Uzbekistan  UZB  2023            72.3884

[1337 rows x 4 columns]

In [ ]:
df.set_index("Pais")

            code  year  life_expectancy_0
Pais
Afghanistan  AFG  1950            28.1563
Afghanistan  AFG  1951            28.5836
Afghanistan  AFG  1952            29.0138
Afghanistan  AFG  1953            29.4521
Afghanistan  AFG  1954            29.6975
...          ...   ...                ...
Zimbabwe     ZWE  2019            61.0603
Zimbabwe     ZWE  2020            61.5300
Zimbabwe     ZWE  2021            60.1347
Zimbabwe     ZWE  2022            62.3601
Zimbabwe     ZWE  2023            62.7748

[21565 rows x 3 columns]

In [17]:
df.head()

          Pais code  year  life_expectancy_0
0  Afghanistan  AFG  1950            28.1563
1  Afghanistan  AFG  1951            28.5836
2  Afghanistan  AFG  1952            29.0138
3  Afghanistan  AFG  1953            29.4521
4  Afghanistan  AFG  1954            29.6975

In [18]:
df.set_index(["code", "year"])

                  Pais  life_expectancy_0
code year
AFG  1950  Afghanistan            28.1563
     1951  Afghanistan            28.5836
     1952  Afghanistan            29.0138
     1953  Afghanistan            29.4521
     1954  Afghanistan            29.6975
...                ...                ...
ZWE  2019     Zimbabwe            61.0603
     2020     Zimbabwe            61.5300
     2021     Zimbabwe            60.1347
     2022     Zimbabwe            62.3601
     2023     Zimbabwe            62.7748

[21565 rows x 2 columns]

In [ ]:
df.loc[df["code"].isnull()] #filtro para saber que valores tienen nulos en code  
#filtro de la columna code para encontrar los nulos

                                        Pais code  year  life_expectancy_0
375                                 Americas  NaN  1770            34.8000
376                                 Americas  NaN  1830            34.8000
377                                 Americas  NaN  1850            35.1000
378                                 Americas  NaN  1870            35.1000
379                                 Americas  NaN  1900            41.0000
...                                      ...  ...   ...                ...
17703  Small Island Developing States (SIDS)  NaN  2019            72.0847
17704  Small Island Developing States (SIDS)  NaN  2020            71.7761
17705  Small Island Developing States (SIDS)  NaN  2021            69.8938
17706  Small Island Developing States (SIDS)  NaN  2022            72.1257
17707  Small Island Developing States (SIDS)  NaN  2023            72.7255

[1348 rows x 4 columns]

In [24]:
df.loc[df["code"].notnull(),["entity","year","life_expectancy_0"]].head()
#datos de la columna code que no son nulos

        entity  year  life_expectancy_0
0  Afghanistan  1950            28.1563
1  Afghanistan  1951            28.5836
2  Afghanistan  1952            29.0138
3  Afghanistan  1953            29.4521
4  Afghanistan  1954            29.6975

In [ ]:
#elimina todas las filas donde la columa code este vacia (NaN)
df.dropna(subset=["code"],inplace=True) #dropna elimina 
df.isnull().sum()

Pais                 0
code                 0
year                 0
life_expectancy_0    0
dtype: int64

In [32]:
df.shape

(20217, 4)

In [38]:
resultado = (
    df.groupby("entity")["life_expectancy_0"]
    .mean()
    .sort_values(ascending=True)
)

In [39]:
resultado.head(10)

entity
USSR                        32.700000
South Sudan                 37.841631
Sierra Leone                43.189605
Mali                        43.760793
Niger                       44.187513
East Timor                  44.684692
Nigeria                     44.855897
Chad                        45.007786
Central African Republic    45.084431
Malawi                      45.554985
Name: life_expectancy_0, dtype: float64

In [47]:
df_1980 = df[(df["year"] >= 1910) & (df["year"] <= 1910) ]
resultado = (
    df_1980.groupby("entity")["life_expectancy_0"]
    .mean()
    .sort_values(ascending=True))
resultado.head(10)

entity
Guatemala     24.0
Bolivia       28.0
Mexico        28.0
Paraguay      29.0
Venezuela     29.0
Chile         30.0
Kazakhstan    30.6
Brazil        31.0
Colombia      31.0
Costa Rica    33.0
Name: life_expectancy_0, dtype: float64